# Generated by Django 5.2.14 on 2026-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
